@echo off
call tomysql < zap_categs2.sql
call tomysql < salary_categ2.sql
call tomysql < amazon_categ2.sql
call tomysql < arbella_categ2.sql
call tomysql < coastal_categ2.sql
call tomysql < klarna_categ2.sql
call tomysql < metlife_categ2.sql
call tomysql < atm_wd_categ2.sql
call tomysql < jetties_categ2.sql
call tomysql < brown_dog_categ2.sql
call tomysql < subway_categ2.sql
call tomysql < dunkin_categ2.sql
call tomysql < pizza_categ2.sql
call tomysql < car_payment_categ2.sql
call tomysql < cumberland_farms_categ2.sql
call tomysql < richdale_categ2.sql
call tomysql < unemployment_categ2.sql
call tomysql < zelle_to_jo_categ2.sql
call tomysql < zelle_to_miranda_categ2.sql
call tomysql < 25_east_rent_categ2.sql
call tomysql < umich_tuition_categ2.sql
call tomysql < umich_rent_categ2.sql
call tomysql < patreon_categ2.sql
call tomysql < shaws_categ2.sql
call tomysql < ezpass_categ2.sql
call tomysql < boston_parking_categ2.sql
call tomysql < verizon_wireless_categ2.sql
call tomysql < riverview_categ2.sql
call tomysql < rowley_pharmacy_categ2.sql
call tomysql < nytimes_categ2.sql
call tomysql < sandpiper_bakery_categ2.sql
call tomysql < dellaria_categ2.sql
call tomysql < checks_categ2.sql
call tomysql < lahey_categ2.sql
call tomysql < ipswich_tavern_categ2.sql
call tomysql < bay_state_physical_therapy_categ2.sql
call tomysql < cvs_categ2.sql
call tomysql < gas_stations_categ2.sql
call tomysql < kindle_categ2.sql
call tomysql < henrys_categ2.sql
call tomysql < paramount_categ2.sql
call tomysql < mirandas_health_insurance_categ2.sql
call tomysql < 25_east_oil_categ2.sql
call tomysql < hart_house_categ2.sql
call tomysql < mirandas_simplebills_categ2.sql
call tomysql < mcafee_categ2.sql
call tomysql < huddys_categ2.sql
call tomysql < comcast_categ2.sql
call tomysql < alfredos_categ2.sql
call tomysql < giuseppes_categ2.sql
call tomysql < fox_creek_categ2.sql
call tomysql < boat_house_categ2.sql
call tomysql < amtrak_categ2.sql
call tomysql < ipswich_bottle_shop_categ2.sql
call tomysql < wire_transfer_fee_categ2.sql
call tomysql < pick_n_bite_categ2.sql
call tomysql < usps_categ2.sql
call tomysql < commuter_rail_categ2.sql
call tomysql < bath_and_body_categ2.sql
call tomysql < mbta_categ2.sql
call tomysql < wikimedia_categ2.sql
call tomysql < cobra_categ2.sql
call tomysql < big_pig_categ2.sql
call tomysql < true_north_categ2.sql
call tomysql < marcorelles_categ2.sql
call tomysql < ipswich_shellfish_categ2.sql
call tomysql < spice_thai_categ2.sql
call tomysql < heart_and_soul_categ2.sql
call tomysql < rowley_pharmacy_categ2.sql
call tomysql < deposits_categ2.sql
call tomysql < rite_aid_categ2.sql
call tomysql < salt_categ2.sql
call tomysql < the_landing_categ2.sql
call tomysql < ipswich_ale_categ2.sql
call tomysql < crosbys_categ2.sql
call tomysql < conleys_categ2.sql
call tomysql < weathervane_categ2.sql
call tomysql < smart_llc_categ2.sql
call tomysql < boston_parking_categ2.sql
call tomysql < legal_sea_foods_categ2.sql
call tomysql < terry_oreillys_categ2.sql
call tomysql < five_guys_categ2.sql
call tomysql < citibank_categ2.sql
call tomysql < market_basket_categ2.sql
call tomysql < pay_by_plate_categ2.sql
call tomysql < pokergo_categ2.sql
call tomysql < whole_foods_categ2.sql
call tomysql < hale_street_categ2.sql
call tomysql < soma_categ2.sql
call tomysql < srh_categ2.sql
call tomysql < donald_b_nelson_categ2.sql
call tomysql < ithaki_categ2.sql
call tomysql < cygnet_categ2.sql
call tomysql < apple_categ2.sql
call tomysql < barnes_and_noble_categ2.sql
call tomysql < vino_divino_categ2.sql
call tomysql < family_dollar_categ2.sql
call tomysql < medicare_premium_categ2.sql
call tomysql < bcbs_premium_categ2.sql
call tomysql < blue_medicarerx_categ2.sql
call tomysql < cable_gardens_categ2.sql
call tomysql < ipswich_utility_categ2.sql
call tomysql < 15_walnut_categ2.sql
call tomysql < social_security_categ2.sql
call tomysql < eft_from_fidelity_categ2.sql
call tomysql < zelle_from_jo_categ2.sql
call tomysql < blue_marlin_categ2.sql
call tomysql < kohls_categ2.sql
call tomysql < mirandas_used_car_categ2.sql
call tomysql < paypal_categ2.sql
call tomysql < laundry_categ2.sql
call tomysql < etsy_categ2.sql
call tomysql < venmo_categ2.sql
call tomysql < penny_dell_categ2.sql
call tomysql < store_ipswich_categ2.sql
call tomysql < dairy_queen_categ2.sql
call tomysql < instamed_categ2.sql
call tomysql < staples_categ2.sql
